apiVersion: batch/v1
kind: Job
metadata:
  name: tweet-block-job
spec:
  template:
    spec:
      containers:
      - name: tweet-block-job
        image: yash5090/tweet-block:latest
        ports:
        - containerPort: 3000
      restartPolicy: OnFailure
