apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-block-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: tweet-block
  template:
    metadata:
      labels:
        app: tweet-block
    spec:
      containers:
        - name: tweet-block
          image: yash5090/tweet-block:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
